"""CLI commands for managing decisions."""

import json
import click
from typing import Optional
from pathlib import Path
from tabulate import tabulate

from noorlytics.decision_store import DecisionStore
from noorlytics.assessment import Priority, DecisionCategory


@click.group()
def decisions():
    """Manage and query stored decisions from assessments.
    
    DESCRIPTION:
    Access decisions generated by 'noor assess' command. Decisions are:
    - Business-prioritized (P1=Critical to P4=Enhancement)
    - Tracked over time with versioning
    - Searchable by priority, customer, manifest
    - Exportable to multiple formats
    
    SUBCOMMANDS:
    - list       List decisions with optional filtering
    - show       View detailed decision information  
    - export     Export decisions to JSON/CSV/Markdown
    
    EXAMPLES:
    - noor decisions list                           # All decisions
    - noor decisions list --priority P1             # Only critical
    - noor decisions list --customer "Acme Corp"    # Customer-specific
    - noor decisions show DEC-C6D04A0F              # Full details
    - noor decisions export --format json           # Export all
    """
    pass


@decisions.command(name="list")
@click.option(
    "--customer",
    type=str,
    help="Filter by customer name",
)
@click.option(
    "--priority",
    type=click.Choice(["P1", "P2", "P3", "P4"], case_sensitive=False),
    help="Filter by priority level",
)
@click.option(
    "--manifest",
    type=str,
    help="Filter by manifest file path",
)
@click.option(
    "--days",
    type=int,
    help="Show decisions from last N days",
)
@click.option(
    "--format",
    type=click.Choice(["table", "json", "csv", "markdown"]),
    default="table",
    help="Output format (default: table)",
)
@click.option(
    "--limit",
    type=int,
    default=20,
    help="Maximum results to return (default: 20)",
)
@click.option(
    "--db",
    type=click.Path(),
    default=None,
    help="Path to decisions database",
)
def list_decisions(
    customer: Optional[str],
    priority: Optional[str],
    manifest: Optional[str],
    days: Optional[int],
    format: str,
    limit: int,
    db: Optional[str],
):
    """List decisions with optional filtering.
    
    PURPOSE:
    Query stored decisions from the database with flexible filtering.
    
    PARAMETERS:
    - --customer: Filter by customer name
    - --priority: Filter by priority (P1, P2, P3, P4)
      * P1 = Critical security/compliance issues
      * P2 = High-impact risks (within weeks)
      * P3 = Medium-term improvements
      * P4 = Low-priority enhancements
    - --manifest: Filter by source file (e.g., requirements.txt)
    - --days: Show only decisions from last N days
    - --format: Output format (table, json, csv, markdown)
    - --limit: Maximum results (default: 20)
    - --db: Custom database path
    
    EXAMPLES:
    - noor decisions list                           # All decisions
    - noor decisions list --priority P1             # Only critical
    - noor decisions list --customer "Acme Corp"    # For specific customer
    - noor decisions list --format json             # JSON format
    - noor decisions list --days 7 --limit 50       # Last week, up to 50
    """
    try:
        store = DecisionStore(db)
        
        # Convert priority string to enum if provided
        priority_enum = None
        if priority:
            priority_enum = Priority[priority.upper()]
        
        # Query decisions
        decisions_list = store.query_decisions(
            customer_name=customer,
            priority=priority_enum,
            category=None,
            manifest_path=manifest,
            days=days,
            limit=limit,
        )
        
        if not decisions_list:
            click.echo("No decisions found matching the criteria.")
            return
        
        if format == "json":
            # Convert to JSON-serializable format
            output = []
            for d in decisions_list:
                output.append({
                    "id": d.id,
                    "priority": d.priority.value,
                    "title": d.title,
                    "category": d.category.value,
                    "rationale": d.rationale[:100] + "..." if len(d.rationale) > 100 else d.rationale,
                    "owner_hint": d.owner_hint,
                    "target_timeframe": d.target_timeframe,
                    "business_impact": d.business_impact,
                })
            click.echo(json.dumps(output, indent=2))
        
        elif format == "csv":
            # CSV format
            output = []
            for d in decisions_list:
                output.append({
                    "Decision ID": d.id,
                    "Priority": d.priority.value,
                    "Title": d.title,
                    "Category": d.category.value,
                    "Owner": d.owner_hint,
                    "Timeframe": d.target_timeframe,
                    "Impact": d.business_impact,
                })
            
            if output:
                headers = output[0].keys()
                rows = [[item.get(h, "") for h in headers] for item in output]
                click.echo("\n".join([",".join(headers)] + [",".join(row) for row in rows]))
        
        elif format == "markdown":
            # Markdown table format
            table_data = []
            for d in decisions_list:
                table_data.append([
                    d.id,
                    d.priority.value,
                    d.title[:40] + "..." if len(d.title) > 40 else d.title,
                    d.category.value,
                    d.owner_hint,
                    d.target_timeframe,
                ])
            
            headers = ["Decision ID", "Priority", "Title", "Category", "Owner", "Timeframe"]
            click.echo(tabulate(table_data, headers=headers, tablefmt="github"))
        
        else:  # table format (default)
            table_data = []
            for d in decisions_list:
                table_data.append([
                    d.id,
                    d.priority.value,
                    d.title[:40] + "..." if len(d.title) > 40 else d.title,
                    d.category.value,
                    d.owner_hint,
                    d.target_timeframe,
                ])
            
            headers = ["Decision ID", "Priority", "Title", "Category", "Owner", "Timeframe"]
            click.echo(tabulate(table_data, headers=headers, tablefmt="grid"))
        
        click.echo(f"\nTotal: {len(decisions_list)} decision(s)")
    
    except Exception as e:
        click.echo(f"Error listing decisions: {e}", err=True)
        raise click.Abort()


@decisions.command(name="show")
@click.argument("decision_id")
@click.option(
    "--verbose",
    is_flag=True,
    help="Include full metadata and audit trail",
)
@click.option(
    "--format",
    type=click.Choice(["text", "json", "markdown"]),
    default="text",
    help="Output format",
)
@click.option(
    "--db",
    type=click.Path(),
    default=None,
    help="Path to decisions database",
)
def show_decision(
    decision_id: str,
    verbose: bool,
    format: str,
    db: Optional[str],
):
    """Show detailed information about a specific decision.
    
    PURPOSE:
    Display complete decision details including:
    - Priority and category
    - Full rationale and recommendations
    - Affected packages and evidence
    - Owner assignment and timeframe
    - Business impact assessment
    
    PARAMETERS:
    - decision_id (required): ID of decision to display (e.g., DEC-C6D04A0F)
    - --verbose: Include full metadata and audit trail
    - --format: Output format (text, json, markdown)
      * text (default): Terminal-formatted display
      * json: Machine-readable JSON
      * markdown: Markdown document format
    - --db: Custom database path
    
    EXAMPLES:
    - noor decisions show DEC-001                   # Show decision
    - noor decisions show DEC-001 --verbose         # With full details
    - noor decisions show DEC-001 --format json     # JSON format
    - noor decisions show DEC-001 --format markdown # Markdown format
    """
    try:
        store = DecisionStore(db)
        decision = store.get_decision(decision_id)
        
        if not decision:
            click.echo(f"Decision {decision_id} not found.", err=True)
            raise click.Abort()
        
        if format == "json":
            output = {
                "id": decision.id,
                "priority": decision.priority.value,
                "title": decision.title,
                "category": decision.category.value,
                "rationale": decision.rationale,
                "recommended_action": decision.recommended_action,
                "owner_hint": decision.owner_hint,
                "target_timeframe": decision.target_timeframe,
                "effort_estimate": decision.effort_estimate,
                "business_impact": decision.business_impact,
                "affected_packages": decision.affected_packages,
                "evidence_ids": decision.evidence_ids,
            }
            click.echo(json.dumps(output, indent=2))
        
        elif format == "markdown":
            md = f"""# Decision: {decision.title}

**ID**: {decision.id}
**Priority**: {decision.priority.value}
**Category**: {decision.category.value}

## Summary
{decision.rationale}

## Details
- **Owner**: {decision.owner_hint}
- **Target Timeframe**: {decision.target_timeframe}
- **Effort Estimate**: {decision.effort_estimate}
- **Business Impact**: {decision.business_impact}

## Affected Packages
{chr(10).join(f"- {pkg}" for pkg in decision.affected_packages) if decision.affected_packages else "None"}

## Recommended Action
{decision.recommended_action}

## Evidence
{chr(10).join(f"- {eid}" for eid in decision.evidence_ids) if decision.evidence_ids else "None"}
"""
            click.echo(md)
        
        else:  # text format (default)
            click.echo(f"\n{'='*60}")
            click.echo(f"Decision ID:      {decision.id}")
            click.echo(f"Title:            {decision.title}")
            click.echo(f"Priority:         {decision.priority.value}")
            click.echo(f"Category:         {decision.category.value}")
            click.echo(f"{'='*60}")
            click.echo(f"\nRationale:\n{decision.rationale}")
            click.echo(f"\nRecommended Action:\n{decision.recommended_action}")
            click.echo(f"\nDetails:")
            click.echo(f"  Owner:              {decision.owner_hint}")
            click.echo(f"  Target Timeframe:   {decision.target_timeframe}")
            click.echo(f"  Effort Estimate:    {decision.effort_estimate}")
            click.echo(f"  Business Impact:    {decision.business_impact}")
            
            if decision.affected_packages:
                click.echo(f"\nAffected Packages:")
                for pkg in decision.affected_packages:
                    click.echo(f"  - {pkg}")
            
            if decision.evidence_ids:
                click.echo(f"\nEvidence:")
                for eid in decision.evidence_ids:
                    click.echo(f"  - {eid}")
            
            if verbose:
                click.echo(f"\n{'='*60}")
                click.echo("Additional Metadata:")
                click.echo(f"  Tradeoff Summary: {decision.tradeoff_summary}")
            
            click.echo(f"\n{'='*60}\n")
    
    except Exception as e:
        click.echo(f"Error retrieving decision: {e}", err=True)
        raise click.Abort()


@decisions.command(name="export")
@click.option(
    "--customer",
    type=str,
    help="Filter by customer name",
)
@click.option(
    "--priority",
    type=click.Choice(["P1", "P2", "P3", "P4"], case_sensitive=False),
    help="Filter by priority level",
)
@click.option(
    "--format",
    type=click.Choice(["json", "csv", "markdown"]),
    default="json",
    help="Export format (default: json)",
)
@click.option(
    "--output",
    type=click.Path(),
    default=None,
    help="Output file path (default: stdout)",
)
@click.option(
    "--db",
    type=click.Path(),
    default=None,
    help="Path to decisions database",
)
def export_decisions(
    customer: Optional[str],
    priority: Optional[str],
    format: str,
    output: Optional[str],
    db: Optional[str],
):
    """Export decisions in multiple formats for integration and reporting.
    
    PURPOSE:
    Extract and export decisions to various formats for:
    - Integration with external tools
    - Excel/spreadsheet analysis
    - Report generation
    - Data sharing with stakeholders
    
    PARAMETERS:
    - --customer: Filter by customer name before export
    - --priority: Filter by priority level (P1, P2, P3, P4)
    - --format: Export format (json, csv, markdown)
      * json: Machine-readable, structures nested data
      * csv: Spreadsheet-compatible, flat table
      * markdown: Human-readable report format
    - --output: File path to save export (default: stdout/terminal)
    - --db: Custom database path
    
    EXAMPLES:
    - noor decisions export --format json --output decisions.json
    - noor decisions export --format csv > decisions.csv
    - noor decisions export --priority P1 --format markdown
    - noor decisions export --customer "Acme Corp" --format json --output acme_decisions.json
    """
    try:
        store = DecisionStore(db)
        
        # Convert priority string to enum if provided
        priority_enum = None
        if priority:
            priority_enum = Priority[priority.upper()]
        
        # Get export data
        export_data = store.export_decisions(
            format=format,
            customer_name=customer,
            priority=priority_enum,
        )
        
        if output:
            output_path = Path(output)
            output_path.parent.mkdir(parents=True, exist_ok=True)
            output_path.write_text(export_data)
            click.echo(f"Export saved to {output}")
        else:
            click.echo(export_data)
    
    except Exception as e:
        click.echo(f"Error exporting decisions: {e}", err=True)
        raise click.Abort()


if __name__ == "__main__":
    decisions()
